import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  llmsSidebar: [
    'intro',
    {
      type: 'category',
      label: '基础知识',
      items: [{type: 'autogenerated', dirName: '01-basics'}],
    },
    {
      type: 'category',
      label: '训练',
      items: [{type: 'autogenerated', dirName: '02-training'}],
    },
  ],
};

export default sidebars;
