import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Agent 介绍',
      items: [{type: 'autogenerated', dirName: '00-agent-intro'}],
    },
    {
      type: 'category',
      label: '大语言模型',
      items: [{type: 'autogenerated', dirName: '01-llm-intro'}],
    },
    {
      type: 'category',
      label: '提示词工程',
      items: [{type: 'autogenerated', dirName: '02-prompt-engineering'}],
    },
    {
      type: 'category',
      label: 'Agent 应用',
      items: [{type: 'autogenerated', dirName: '03-agent-application'}],
    },
  ],
  paperReadingSidebar: [
    {
      type: 'category',
      label: '论文领读',
      items: [{type: 'autogenerated', dirName: '05-paper-reading'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
